version: '3.8'

services:

  # === Backend ===
  backend:
    image: bonghyerin/prham-backend:${IMAGE_TAG:-latest}
    container_name: app-backend
    env_file:
      - ./backend/.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://app-mysql:3306/prham?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Rocm316497!
      SPRING_DATA_MONGODB_URI: mongodb://admin:rocm316497!@app-mongodb:27017/prham_db?authSource=admin
      SSAFY_SSO_CLIENT_ID: ${SSAFY_SSO_CLIENT_ID}
      SSAFY_SSO_CLIENT_SECRET: ${SSAFY_SSO_CLIENT_SECRET}
      SSAFY_SSO_REDIRECT_URI: https://pyeonriham.site/login/oauth2/code/ssafy
      SSAFY_SSO_TOKEN_REQUEST_URL: https://project.ssafy.com/ssafy/oauth2/token
      SSAFY_SSO_USER_INFO_URL: https://project.ssafy.com/ssafy/user/me
      SSAFY_OPENAPI_KEY: ${SSAFY_OPENAPI_KEY}
      SSAFY_OPENAPI_USER_DETAIL_URL: https://project.ssafy.com/ssafy/api/user/detail
      TZ: Asia/Seoul
    expose:
      - "8080"
    restart: always
    networks:
      - app-net



  # === Frontend ===
  frontend:
    image: bonghyerin/prham-frontend:${IMAGE_TAG:-latest}
    container_name: app-frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-net


  # === Nginx Gateway ===
  nginx:
    build: ./nginx
    container_name: app-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - app-net



volumes:
  jenkins-data:

networks:
  app-net:
    external: true
