version: '3.8'

services:
  # 데이터베이스 (MySQL)
  mysql:
    image: 'mysql:8.0'
    container_name: 'pyeonriham-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - pyeonriham_mysql_data:/var/lib/mysql
    restart: always
    networks:
      - pyeonriham_network

  # 인메모리 캐시 (Redis)
  redis:
    image: 'redis:alpine'
    container_name: 'pyeonriham-redis'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - pyeonriham_redis_data:/data
    restart: always
    networks:
      - pyeonriham_network

  # CI/CD 서버 (Jenkins)
  jenkins:
    build: ./jenkins # jenkins 폴더에 Dockerfile이 있어야 함
    container_name: 'pyeonriham-jenkins'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # 호스트의 Docker를 제어
    restart: always
    networks:
      - pyeonriham_network

# 서비스들이 함께 통신할 네트워크 정의
networks:
  pyeonriham_network:
    driver: bridge

# 데이터 영속성을 위한 볼륨 정의
volumes:
  pyeonriham_mysql_data:
  pyeonriham_redis_data:
