server {
    listen 80;
    server_name k13a105.p.ssafy.io;

    root /usr/share/nginx/html;
    index index.html;

    # 정적 리소스는 그대로 제공
    location /assets/ {
        try_files $uri =404;
    }

    location /images/ {
        try_files $uri =404;
    }

    location /favicon.png {
        try_files $uri =404;
    }

    # 나머지 모든 경로는 React 라우터 처리
    location / {
        try_files $uri /index.html;
    }
}
